version: "3.3"
services:
  app:
    user: root
    build: "./container"
    working_dir: "/attestation/"
    volumes:
      - ./:/attestation/:z
      - /sys/class/tpm/tpm0/:/sys/class/tpm/tpm0/
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/tpm0:/dev/tpm0
      - /dev/tpmrm0:/dev/tpmrm0
    environment:
      - EDITOR=vim
      - DISPLAY=${DISPLAY}
      - ECDAA_CURVES=FP256BN
      - TPM2TOOLS_TCTI="device:/dev/tpm0"
      - LD_LIBRARY_PATH=/usr/local/lib/

    command: sleep infinity
    # sh -c "/attestation/container/run.sh"
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - 8080:8080
    profiles:
      - default

  android_lib:
    build: ./android
    volumes:
      - ./core:/core
      - ./thirdparty:/thirdparty
    command:  bash -c 'go get golang.org/x/mobile/bind && gomobile bind -v -o scrappy_crypto.aar -target=android'
    working_dir: /core
    profiles:
      - android_lib
