version: '3'
services:
  app:
    build: ./lib
    volumes:
      - ./lib/:/app
      - ./lib/ndk/ndk:/ndk
      - ./lib/ndk/ndk-bin:/ndk-bin
      - ./scrappy/app/src/main/jniLibs:/out
      - ./data/app/registry:/usr/local/cargo/registry/
    command: sh /app/main.sh
