[package]
name = "ecdaa-android"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.19"
rand = "0.8.5"
ecdaa = { git = "https://github.com/akakou/ecdaa-rs", features=["std"] }
serde_json = "^1.0"